---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/panoramaadvisory.ca/
    - /usr/bin/rsync -a --exclude='.git/' --exclude='.cpanel.yml' --exclude='contact/smtp-config.php' --exclude='contact/smtp-debug.log' --exclude='contact/error_log' --exclude='.user.ini' --exclude='php.ini' ./ "$DEPLOYPATH"
